### ISSUE TITLE
truffle readthedocs: This page does not exist yet.

### ISSUE THREAD

**Issue by Allmentux** [zeriontech/the-token-fund-smart-contracts#5]
If one clicks on the link for: 

For more information about truffle visit https://truffle.readthedocs.io/en/latest/

This appears:

      \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

Is  this supposed to be correct?

**Comment by bashalex** [comment]
Nope, thank you! We will fix the link.
